<a href="https://colab.research.google.com/github/Dracarys38/Machyne-navchanya/blob/main/%22%D0%9B%D0%B0%D0%B1%D0%BE%D1%80%D0%B0%D1%82%D0%BE%D1%80%D0%BD%D0%B0_%D1%80%D0%BE%D0%B1%D0%BE%D1%82%D0%B0_%E2%84%961_%D0%9C%D0%9D%2C_%D0%9F%D0%BE%D1%81%D1%82%D0%B5%D0%BB%D1%8C%D0%BD%D1%8F%D0%BA_%D0%86%D0%B3%D0%BE%D1%80_%D0%A1%D0%B5%D1%80%D0%B3%D1%96%D0%B9%D0%BE%D0%B2%D0%B8%D1%87_%D0%A4%D0%86%D0%A2_3_15%2C_10_%D0%B2%D0%B0%D1%80%D1%96%D0%B0%D0%BD%D1%82_ipynb%22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
# Постельняк Ігор Сергійович ФІТ 3-15
# Варіант 10

# Завдання 1
# 10. Створіть одновимірний масив (вектор) з перших 10 піднесених до квадрату натуральних чисел та виведіть його значення.
import numpy as np
vector10 = np.array([i**2 for i in range(1, 11)])
print("Завдання 1.10:", vector10)

Завдання 1.10: [  1   4   9  16  25  36  49  64  81 100]


In [4]:
# Завдання 2
# 10. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його значеннями квадратних коренів від кожного натурального числа, починаючи з 1, та виведіть його значення.
import numpy as np
import math
matrix10 = np.array([[math.sqrt(i*3 + j + 1) for j in range(3)] for i in range(3)])
print("Завдання 2.10:")
print(matrix10)

Завдання 2.10:
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]]


In [5]:
# Завдання 3
# 10. Створіть масив розміром 3x3, заповніть його випадковими цілими числами в діапазоні від 0 до 5 та виведіть його значення.
import numpy as np
matrix10 = np.random.randint(0, 6, (3, 3))
print("Завдання 3.10:")
print(matrix10)

Завдання 3.10:
[[2 4 4]
 [2 2 0]
 [2 1 4]]


In [6]:
# Завдання 4
# 10. Створіть масив розміром 5x5, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та обчисліть суму елементів, які менше середнього значення.
import numpy as np
matrix = np.random.rand(5, 5)
mean_val = np.mean(matrix)
sum_less = np.sum(matrix[matrix < mean_val])
print("Завдання 4.10:")
print("Матриця:")
print(matrix)
print(f"Середнє: {mean_val:.4f}")
print(f"Сума елементів менших за середнє: {sum_less:.4f}")

Завдання 4.10:
Матриця:
[[8.85117225e-01 9.47479695e-04 4.21558407e-01 2.99388165e-01
  5.72819278e-01]
 [8.09352757e-01 8.46272832e-01 5.09271776e-01 9.90286995e-01
  4.47682137e-02]
 [7.08279094e-01 2.99716328e-01 6.42847289e-01 5.93183152e-01
  9.98186062e-01]
 [7.45296827e-01 4.66356035e-01 4.35201192e-01 8.85716675e-02
  9.17331288e-01]
 [2.77510532e-01 7.16670745e-01 1.93620407e-01 7.95209126e-01
  4.28996702e-01]]
Середнє: 0.5475
Сума елементів менших за середнє: 3.4659


In [7]:
# Завдання 5
# 10. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами від 1 до 30 та виконайте на них поелементні операції додавання, віднімання та множення.
import numpy as np
arr1 = np.random.randint(1, 31, 5)
arr2 = np.random.randint(1, 31, 5)
print("Завдання 5.10:")
print("Масив 1:", arr1)
print("Масив 2:", arr2)
print("Додавання:", arr1 + arr2)
print("Віднімання:", arr1 - arr2)
print("Множення:", arr1 * arr2)

Завдання 5.10:
Масив 1: [16  5 18 14  4]
Масив 2: [11  1  6 19  8]
Додавання: [27  6 24 33 12]
Віднімання: [ 5  4 12 -5 -4]
Множення: [176   5 108 266  32]


In [8]:
# Завдання 6
# Створіть дві матриці 3x3, заповніть їх довільними дійсними числами від 0 до 1 та знайдіть їх добуток.
import numpy as np
matrix1 = np.random.rand(3, 3)
matrix2 = np.random.rand(3, 3)
product = np.dot(matrix1, matrix2)
print("Завдання 6.10:")
print("Матриця 1:")
print(matrix1)
print("Матриця 2:")
print(matrix2)
print("Добуток матриць:")
print(product)

Завдання 6.10:
Матриця 1:
[[0.92007781 0.14285684 0.78962467]
 [0.88943898 0.83527996 0.96669219]
 [0.32598435 0.35407455 0.94864078]]
Матриця 2:
[[0.60994008 0.21658804 0.97643524]
 [0.57206841 0.78565276 0.77352166]
 [0.93198329 0.84888711 0.61451193]]
Добуток матриць:
[[1.37883322 0.98181593 1.49413304]
 [1.92128273 1.66949439 2.10863059]
 [1.28550315 1.1540729  1.17513802]]


In [9]:
# Завдання 7
# Створіть дві матриці розміром 2x3 та 3x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 5 та перемножте їх між собою.
import numpy as np
matrix1 = np.random.randint(1, 6, (2, 3))
matrix2 = np.random.randint(1, 6, (3, 2))
product = np.dot(matrix1, matrix2)
print("Завдання 7.10:")
print("Матриця 2x3:")
print(matrix1)
print("Матриця 3x2:")
print(matrix2)
print("Добуток:")
print(product)

Завдання 7.10:
Матриця 2x3:
[[5 5 4]
 [1 5 2]]
Матриця 3x2:
[[3 1]
 [4 2]
 [3 4]]
Добуток:
[[47 31]
 [29 19]]


In [10]:
# Завдання 8
# Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.
import numpy as np
matrix = np.random.randint(1, 11, (3, 3))
try:
    inv_matrix = np.linalg.inv(matrix)
    print("Завдання 8.10:")
    print("Початкова матриця:")
    print(matrix)
    print("Обернена матриця:")
    print(inv_matrix)
except np.linalg.LinAlgError:
    print("Матриця вироджена, оберненої не існує")

Завдання 8.10:
Початкова матриця:
[[ 6  5  4]
 [ 9  7  3]
 [10  4  3]]
Обернена матриця:
[[-0.13432836 -0.01492537  0.19402985]
 [-0.04477612  0.32835821 -0.26865672]
 [ 0.50746269 -0.3880597   0.04477612]]


In [11]:
# Завдання 9
# Створіть матрицю розміром 5x5, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.
import numpy as np
matrix = np.random.rand(5, 5)
transposed = matrix.T
print("Завдання 9.10:")
print("Початкова матриця:")
print(matrix)
print("Транспонована матриця:")
print(transposed)

Завдання 9.10:
Початкова матриця:
[[0.00648525 0.09181812 0.97512546 0.12595068 0.93733952]
 [0.87610337 0.51794409 0.8733148  0.58553868 0.39499008]
 [0.08158601 0.62546753 0.90176907 0.6676356  0.39326614]
 [0.91164175 0.59041655 0.49907623 0.38600523 0.89205253]
 [0.57610255 0.77354779 0.99068733 0.83403856 0.08481012]]
Транспонована матриця:
[[0.00648525 0.87610337 0.08158601 0.91164175 0.57610255]
 [0.09181812 0.51794409 0.62546753 0.59041655 0.77354779]
 [0.97512546 0.8733148  0.90176907 0.49907623 0.99068733]
 [0.12595068 0.58553868 0.6676356  0.38600523 0.83403856]
 [0.93733952 0.39499008 0.39326614 0.89205253 0.08481012]]


In [12]:
# Завдання 10
# Створіть матрицю розміром 3x4 та вектор розміром 4x1, заповніть матрицю випадковими цілими числами в діапазоні від -5 до 5, а вектор - випадковими дійсними числами від 0 до 1 і знайдіть добуток матриці на вектор.
import numpy as np
matrix = np.random.randint(-5, 6, (3, 4))
vector = np.random.rand(4, 1)
result = np.dot(matrix, vector)
print("Завдання 10.10:")
print("Матриця 3x4:")
print(matrix)
print("Вектор 4x1:")
print(vector)
print("Добуток матриці на вектор:")
print(result)

Завдання 10.10:
Матриця 3x4:
[[ 2 -2 -5  5]
 [-1 -1 -3 -1]
 [ 1  4  1 -4]]
Вектор 4x1:
[[0.23007423]
 [0.75708756]
 [0.85373442]
 [0.47250434]]
Добуток матриці на вектор:
[[-2.96017703]
 [-4.02086939]
 [ 2.2221415 ]]


In [13]:
# Завдання 11
# Створіть матрицю розміром 2x3 та вектор розміром 3x1, заповніть матрицю випадковими дійсними числами від 0 до 1, а вектор - випадковими дійсними числами від 0 до 1, і знайдіть добуток матриці на вектор.
import numpy as np
matrix = np.random.rand(2, 3)
vector = np.random.rand(3, 1)
result = np.dot(matrix, vector)
print("Завдання 11.10:")
print("Матриця 2x3:")
print(matrix)
print("Вектор 3x1:")
print(vector)
print("Добуток матриці на вектор:")
print(result)

Завдання 11.10:
Матриця 2x3:
[[0.09424784 0.97949204 0.24014901]
 [0.01584917 0.00805637 0.04822315]]
Вектор 3x1:
[[0.37370586]
 [0.66094502]
 [0.92784589]]
Добуток матриці на вектор:
[[0.90543263]
 [0.05599139]]


In [14]:
# Завдання 12
# Створіть дві матриці розміром 3x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть суму всіх елементів обох матриць.
import numpy as np
matrix1 = np.random.randint(1, 11, (3, 3))
matrix2 = np.random.randint(1, 11, (3, 3))
total_sum = np.sum(matrix1) + np.sum(matrix2)
print("Завдання 12.10:")
print("Матриця 1:")
print(matrix1)
print(f"Сума елементів матриці 1: {np.sum(matrix1)}")
print("Матриця 2:")
print(matrix2)
print(f"Сума елементів матриці 2: {np.sum(matrix2)}")
print(f"Загальна сума: {total_sum}")

Завдання 12.10:
Матриця 1:
[[ 4  8 10]
 [ 2  6  3]
 [ 8  8  1]]
Сума елементів матриці 1: 50
Матриця 2:
[[7 8 5]
 [1 5 2]
 [4 9 9]]
Сума елементів матриці 2: 50
Загальна сума: 100


In [15]:
# Завдання 13
# Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть різницю їх елементів.
import numpy as np
matrix1 = np.random.randint(1, 11, (2, 2))
matrix2 = np.random.randint(1, 11, (2, 2))
difference = matrix1 - matrix2
print("Завдання 13.10:")
print("Матриця 1:")
print(matrix1)
print("Матриця 2:")
print(matrix2)
print("Різниця (матриця1 - матриця2):")
print(difference)

Завдання 13.10:
Матриця 1:
[[1 4]
 [7 8]]
Матриця 2:
[[2 5]
 [1 2]]
Різниця (матриця1 - матриця2):
[[-1 -1]
 [ 6  6]]


In [16]:
# Завдання 14
# Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 5 та знайдіть кількість парних елементів матриці.
import numpy as np
matrix = np.random.randint(1, 6, (3, 3))
even_count = np.sum(matrix % 2 == 0)
print("Завдання 14.10:")
print("Матриця 3x3:")
print(matrix)
print(f"Кількість парних елементів: {even_count}")

Завдання 14.10:
Матриця 3x3:
[[3 2 2]
 [3 3 5]
 [3 5 3]]
Кількість парних елементів: 2


In [17]:
# Завдання 15
# Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від -1 до 1 та знайдіть вектор-стовпчик, що містить суму кубів елементів кожного рядка матриці.
import numpy as np
matrix = np.random.uniform(-1, 1, (4, 4))
cubes_sum = np.sum(matrix**3, axis=1).reshape(-1, 1)
print("Завдання 15.10:")
print("Матриця 4x4:")
print(matrix)
print("Вектор-стовпчик сум кубів елементів кожного рядка:")
print(cubes_sum)

Завдання 15.10:
Матриця 4x4:
[[ 0.55517179 -0.46933657  0.7125806  -0.43401381]
 [-0.23813986  0.43420868 -0.56622092 -0.7547451 ]
 [ 0.04243561  0.67933435  0.83319728  0.4580149 ]
 [-0.59149707  0.90267798 -0.64888528 -0.62337381]]
Вектор-стовпчик сум кубів елементів кожного рядка:
[[ 0.34780225]
 [-0.5431076 ]
 [ 0.98808752]
 [ 0.01312611]]


In [18]:
"""
Під час виконання лабораторної роботи з масивами та матрицями в Python було успішно реалізовано
основні операції роботи з векторами та матрицями за допомогою бібліотеки NumPy.
Робота демонструє практичне застосування бібліотеки NumPy для вирішення задач лінійної алгебри
та підготовку даних для подальшого використання в машинному навчанні.
"""

'\nПід час виконання лабораторної роботи з масивами та матрицями в Python було успішно реалізовано\nосновні операції роботи з векторами та матрицями за допомогою бібліотеки NumPy.\nРобота демонструє практичне застосування бібліотеки NumPy для вирішення задач лінійної алгебри\nта підготовку даних для подальшого використання в машинному навчанні.\n'