<a href="https://colab.research.google.com/github/Dracarys38/Machyne-navchanya/blob/main/%22%D0%9B%D0%B0%D0%B1%D0%BE%D1%80%D0%B0%D1%82%D0%BE%D1%80%D0%BD%D0%B0_%D1%80%D0%BE%D0%B1%D0%BE%D1%82%D0%B0_%E2%84%961_%D0%9C%D0%9D%2C_%D0%9F%D0%BE%D1%81%D1%82%D0%B5%D0%BB%D1%8C%D0%BD%D1%8F%D0%BA_%D0%86%D0%B3%D0%BE%D1%80_%D0%A1%D0%B5%D1%80%D0%B3%D1%96%D0%B9%D0%BE%D0%B2%D0%B8%D1%87_%D0%A4%D0%86%D0%A2_3_15%2C_10_%D0%B2%D0%B0%D1%80%D1%96%D0%B0%D0%BD%D1%82_ipynb%22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Постельняк Ігор Сергійович ФІТ 3-15
# Варіант 10

# Завдання 1
# 10. Створіть одновимірний масив (вектор) з перших 10 піднесених до квадрату натуральних чисел та виведіть його значення.
import numpy as np
vector10 = np.array([i**2 for i in range(1, 11)])
print("Завдання 1.10:", vector10)

Завдання 2.10:
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]]


In [ ]:
# Завдання 2
# 10. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його значеннями квадратних коренів від кожного натурального числа, починаючи з 1, та виведіть його значення.
import numpy as np
import math
matrix10 = np.array([[math.sqrt(i*3 + j + 1) for j in range(3)] for i in range(3)])
print("Завдання 2.10:")
print(matrix10)

Завдання 2.10:
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]]


In [ ]:
# Завдання 3
# 10. Створіть масив розміром 3x3, заповніть його випадковими цілими числами в діапазоні від 0 до 5 та виведіть його значення.
import numpy as np
matrix10 = np.random.randint(0, 6, (3, 3))
print("Завдання 3.10:")
print(matrix10)

Завдання 3.10:
[[5 1 4]
 [3 1 4]
 [1 5 0]]


In [ ]:
# Завдання 4
# 10. Створіть масив розміром 5x5, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та обчисліть суму елементів, які менше середнього значення.
import numpy as np
matrix = np.random.rand(5, 5)
mean_val = np.mean(matrix)
sum_less = np.sum(matrix[matrix < mean_val])
print("Завдання 4.10:")
print("Матриця:")
print(matrix)
print(f"Середнє: {mean_val:.4f}")
print(f"Сума елементів менших за середнє: {sum_less:.4f}")

Завдання 4.10:
Матриця:
[[0.32554927 0.44090902 0.39866839 0.09197264 0.22380365]
 [0.58529002 0.93996763 0.76911008 0.75059719 0.68444099]
 [0.45584121 0.46148729 0.8104116  0.57802782 0.49596374]
 [0.46327316 0.05966899 0.3476699  0.93518341 0.03825038]
 [0.37620534 0.81188814 0.48870534 0.69661734 0.36865162]]
Середнє: 0.5039
Сума елементів менших за середнє: 5.0366


In [ ]:
# Завдання 5
# 10. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами від 1 до 30 та виконайте на них поелементні операції додавання, віднімання та множення.
import numpy as np
arr1 = np.random.randint(1, 31, 5)
arr2 = np.random.randint(1, 31, 5)
print("Завдання 5.10:")
print("Масив 1:", arr1)
print("Масив 2:", arr2)
print("Додавання:", arr1 + arr2)
print("Віднімання:", arr1 - arr2)
print("Множення:", arr1 * arr2)

Завдання 5.10:
Масив 1: [18  9 21 11  5]
Масив 2: [14 24  9 13 24]
Додавання: [32 33 30 24 29]
Віднімання: [  4 -15  12  -2 -19]
Множення: [252 216 189 143 120]


In [ ]:
# Завдання 6
# Створіть дві матриці 3x3, заповніть їх довільними дійсними числами від 0 до 1 та знайдіть їх добуток.
import numpy as np
matrix1 = np.random.rand(3, 3)
matrix2 = np.random.rand(3, 3)
product = np.dot(matrix1, matrix2)
print("Завдання 6.10:")
print("Матриця 1:")
print(matrix1)
print("Матриця 2:")
print(matrix2)
print("Добуток матриць:")
print(product)

Завдання 6.10:
Матриця 1:
[[0.76547943 0.34926157 0.56467562]
 [0.19958465 0.39274198 0.45223648]
 [0.53750475 0.6907727  0.65937964]]
Матриця 2:
[[0.69242116 0.73035278 0.58742206]
 [0.59520635 0.95877704 0.99642833]
 [0.9364161  0.78706454 0.95177567]]
Добуток матриць:
[[1.2666882  1.33837016 1.33511814]
 [0.79544068 0.87825849 0.93900734]
 [1.40078567 1.57383942 1.63162913]]


In [ ]:
# Завдання 7
# Створіть дві матриці розміром 2x3 та 3x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 5 та перемножте їх між собою.
import numpy as np
matrix1 = np.random.randint(1, 6, (2, 3))
matrix2 = np.random.randint(1, 6, (3, 2))
product = np.dot(matrix1, matrix2)
print("Завдання 7.10:")
print("Матриця 2x3:")
print(matrix1)
print("Матриця 3x2:")
print(matrix2)
print("Добуток:")
print(product)

Завдання 7.10:
Матриця 2x3:
[[1 5 4]
 [1 3 5]]
Матриця 3x2:
[[2 2]
 [3 1]
 [5 2]]
Добуток:
[[37 15]
 [36 15]]


In [ ]:
# Завдання 8
# Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.
import numpy as np
matrix = np.random.randint(1, 11, (3, 3))
try:
    inv_matrix = np.linalg.inv(matrix)
    print("Завдання 8.10:")
    print("Початкова матриця:")
    print(matrix)
    print("Обернена матриця:")
    print(inv_matrix)
except np.linalg.LinAlgError:
    print("Матриця вироджена, оберненої не існує")

Завдання 8.10:
Початкова матриця:
[[4 2 9]
 [9 8 5]
 [7 9 5]]
Обернена матриця:
[[-0.02702703  0.38378378 -0.33513514]
 [-0.05405405 -0.23243243  0.32972973]
 [ 0.13513514 -0.11891892  0.07567568]]


In [ ]:
# Завдання 9
# Створіть матрицю розміром 5x5, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.
import numpy as np
matrix = np.random.rand(5, 5)
transposed = matrix.T
print("Завдання 9.10:")
print("Початкова матриця:")
print(matrix)
print("Транспонована матриця:")
print(transposed)

Завдання 9.10:
Початкова матриця:
[[0.83613153 0.87951473 0.38093712 0.51685295 0.22832061]
 [0.14907491 0.1001359  0.66117691 0.729585   0.88282687]
 [0.55830723 0.48733163 0.86492796 0.36885818 0.45714044]
 [0.25727821 0.64996519 0.47114919 0.9375182  0.66271447]
 [0.61254682 0.2037127  0.13816949 0.34909386 0.49901806]]
Транспонована матриця:
[[0.83613153 0.14907491 0.55830723 0.25727821 0.61254682]
 [0.87951473 0.1001359  0.48733163 0.64996519 0.2037127 ]
 [0.38093712 0.66117691 0.86492796 0.47114919 0.13816949]
 [0.51685295 0.729585   0.36885818 0.9375182  0.34909386]
 [0.22832061 0.88282687 0.45714044 0.66271447 0.49901806]]


In [ ]:
# Завдання 10
# Створіть матрицю розміром 3x4 та вектор розміром 4x1, заповніть матрицю випадковими цілими числами в діапазоні від -5 до 5, а вектор - випадковими дійсними числами від 0 до 1 і знайдіть добуток матриці на вектор.
import numpy as np
matrix = np.random.randint(-5, 6, (3, 4))
vector = np.random.rand(4, 1)
result = np.dot(matrix, vector)
print("Завдання 10.10:")
print("Матриця 3x4:")
print(matrix)
print("Вектор 4x1:")
print(vector)
print("Добуток матриці на вектор:")
print(result)

Завдання 10.10:
Матриця 3x4:
[[-5 -5  4  5]
 [ 4  1 -5 -2]
 [ 3  0  1  2]]
Вектор 4x1:
[[0.72293082]
 [0.39899169]
 [0.99844579]
 [0.72867661]]
Добуток матриці на вектор:
[[ 2.02755364]
 [-3.1588672 ]
 [ 4.62459146]]


In [ ]:
# Завдання 11
# Створіть матрицю розміром 2x3 та вектор розміром 3x1, заповніть матрицю випадковими дійсними числами від 0 до 1, а вектор - випадковими дійсними числами від 0 до 1, і знайдіть добуток матриці на вектор.
import numpy as np
matrix = np.random.rand(2, 3)
vector = np.random.rand(3, 1)
result = np.dot(matrix, vector)
print("Завдання 11.10:")
print("Матриця 2x3:")
print(matrix)
print("Вектор 3x1:")
print(vector)
print("Добуток матриці на вектор:")
print(result)

Завдання 11.10:
Матриця 2x3:
[[0.02452612 0.74636129 0.30253718]
 [0.25668433 0.68100855 0.43685845]]
Вектор 3x1:
[[0.0717163 ]
 [0.98177364]
 [0.74955225]]
Добуток матриці на вектор:
[[0.96128418]
 [1.01445292]]


In [ ]:
# Завдання 12
# Створіть дві матриці розміром 3x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть суму всіх елементів обох матриць.
import numpy as np
matrix1 = np.random.randint(1, 11, (3, 3))
matrix2 = np.random.randint(1, 11, (3, 3))
total_sum = np.sum(matrix1) + np.sum(matrix2)
print("Завдання 12.10:")
print("Матриця 1:")
print(matrix1)
print(f"Сума елементів матриці 1: {np.sum(matrix1)}")
print("Матриця 2:")
print(matrix2)
print(f"Сума елементів матриці 2: {np.sum(matrix2)}")
print(f"Загальна сума: {total_sum}")

Завдання 12.10:
Матриця 1:
[[10  5  8]
 [ 6  8 10]
 [ 4  7  7]]
Сума елементів матриці 1: 65
Матриця 2:
[[ 7 10  6]
 [ 4  4 10]
 [10 10  2]]
Сума елементів матриці 2: 63
Загальна сума: 128


In [ ]:
# Завдання 13
# Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть різницю їх елементів.
import numpy as np
matrix1 = np.random.randint(1, 11, (2, 2))
matrix2 = np.random.randint(1, 11, (2, 2))
difference = matrix1 - matrix2
print("Завдання 13.10:")
print("Матриця 1:")
print(matrix1)
print("Матриця 2:")
print(matrix2)
print("Різниця (матриця1 - матриця2):")
print(difference)

Завдання 13.10:
Матриця 1:
[[2 5]
 [9 2]]
Матриця 2:
[[6 7]
 [5 9]]
Різниця (матриця1 - матриця2):
[[-4 -2]
 [ 4 -7]]


In [ ]:
# Завдання 14
# Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 5 та знайдіть кількість парних елементів матриці.
import numpy as np
matrix = np.random.randint(1, 6, (3, 3))
even_count = np.sum(matrix % 2 == 0)
print("Завдання 14.10:")
print("Матриця 3x3:")
print(matrix)
print(f"Кількість парних елементів: {even_count}")

Завдання 14.10:
Матриця 3x3:
[[5 3 5]
 [1 1 4]
 [3 1 1]]
Кількість парних елементів: 1


In [ ]:
# Завдання 15
# Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від -1 до 1 та знайдіть вектор-стовпчик, що містить суму кубів елементів кожного рядка матриці.
import numpy as np
matrix = np.random.uniform(-1, 1, (4, 4))
cubes_sum = np.sum(matrix**3, axis=1).reshape(-1, 1)
print("Завдання 15.10:")
print("Матриця 4x4:")
print(matrix)
print("Вектор-стовпчик сум кубів елементів кожного рядка:")
print(cubes_sum)

In [ ]:
"""
Під час виконання лабораторної роботи з масивами та матрицями в Python було успішно реалізовано
основні операції роботи з векторами та матрицями за допомогою бібліотеки NumPy.
Робота демонструє практичне застосування бібліотеки NumPy для вирішення задач лінійної алгебри
та підготовку даних для подальшого використання в машинному навчанні.
"""

'\nПід час виконання лабораторної роботи з масивами та матрицями в Python було успішно реалізовано\nосновні операції роботи з векторами та матрицями за допомогою бібліотеки NumPy.\n'